### ISSUE TITLE
extfilter eats 100% of one CPU

### ISSUE THREAD

**Issue by CEMEHOB** [max197616/extfilter#1]
OS: CentOS 7
Kernel: 3.10.0-327.36.1.el7.x86_64
dpdk-16.07

extfilter compiled correctly, working correctly
but eats 100% of one core.

Please let me know what information you need and which troubleshooting steps I should to do.

PS Let me know, if you prefer Russian language in issues. :)

![2016-10-21_15-40-38](https://cloud.githubusercontent.com/assets/17199443/19598693/cd81c21a-97a4-11e6-8e38-16fe69304cac.png)

**Comment by max197616** [comment]
Приветствую.

Это нормальная работа DPDK, т.к. постоянно происходит поллинг сетевой карты.

**Comment by CEMEHOB** [comment]
Приветствую.
А можно как-то снизить нагрузку, например снизив быстродействие? Есть какие-то настройки?

**Comment by CEMEHOB** [comment]
И еще один вопрос: если процесс все время будет потреблять 100% одного ядра с одной очередью, то как понять, что производительности не хватает для обработки трафика?

**Comment by max197616** [comment]
Я сейчас доделываю версию, которая работает с минимум 2 ядрами - один процесс получает пакеты от сетевой карты, а другой анализирует пакеты с анализом потоков. Таким образом можно рассчитать количество необработанных (потерянных) пакетов.

**Comment by CEMEHOB** [comment]
Спасибо за ответ, будем ждать.
