### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by 31337Ghost** [max197616/extfilter#14]
Есть ли наработки по запуску данной программы в контейнере? DPDK собранный в контейнере находится поиском, но пока не проверял его. Или может быть у вас есть видение что в контейнере точно не заработает и даже пробовать не стоит?

**Comment by max197616** [comment]
Наработок точно нет. DPDK в docker работает. Но честно говоря я не вижу особого смысла запускать в docker, т.к. для dpi требуется много памяти.
