### ISSUE TITLE
Ошибка при сборке ubuntu

### ISSUE THREAD

**Issue by prozaklob** [max197616/extfilter#15]
`Making all in src
make[1]: Entering directory '/root/extfilter/src'
g++ -DHAVE_CONFIG_H -I. -I../include  -I/root/dpdk/build/include -I.././peafowl/src -I.././marisa/include -march=native -mtune=native  -std=c++11 -O3 -Wall -fno-stack-protector -pthread -march=native -mtune=native -mpopcnt -mavx -MT acl.o -MD -MP -MF .deps/acl.Tpo -c -o acl.o acl.cpp
acl.cpp: In member function ‘int ACL::initACL(std::map<std::__cxx11::basic_string<char>, int>&, int, std::set<rte_acl_ctx*>*)’:
acl.cpp:400:174: error: cannot convert ‘uintptr_t* {aka unsigned int*}’ to ‘volatile uint64_t* {aka volatile long long unsigned int*}’ for argument ‘1’ to ‘int rte_atomic64_cmpset(volatile uint64_t*, uint64_t, uint64_t)’
   rte_atomic64_cmpset((uintptr_t*)&extFilter::getLcoreConf(lcore_id)->new_acx_ipv4, (uintptr_t)extFilter::getLcoreConf(lcore_id)->new_acx_ipv4, (uintptr_t)ipv4_acx[socketid]);
                                                                                                                                                                              ^
acl.cpp:401:174: error: cannot convert ‘uintptr_t* {aka unsigned int*}’ to ‘volatile uint64_t* {aka volatile long long unsigned int*}’ for argument ‘1’ to ‘int rte_atomic64_cmpset(volatile uint64_t*, uint64_t, uint64_t)’
   rte_atomic64_cmpset((uintptr_t*)&extFilter::getLcoreConf(lcore_id)->new_acx_ipv6, (uintptr_t)extFilter::getLcoreConf(lcore_id)->new_acx_ipv6, (uintptr_t)ipv6_acx[socketid]);
                                                                                                                                                                              ^
Makefile:376: recipe for target 'acl.o' failed
make[1]: *** [acl.o] Error 1
make[1]: Leaving directory '/root/extfilter/src'
Makefile:346: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by max197616** [comment]
Проверьте версию DPDK, должна быть та, что указана в README.

**Comment by prozaklob** [comment]
> Проверьте версию DPDK, должна быть та, что указана в README.

poco-1.8.1
dpdk-stable-17.05.1
i686-native-linuxapp-gcc
Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz

**Comment by max197616** [comment]
>  i686-native-linuxapp-gcc
Фильтр работает только под x86_64.
