### ISSUE TITLE
Добавьте информацию о версии Cacti для импорта темплейтов

### ISSUE THREAD

**Issue by CEMEHOB** [max197616/extfilter#3]
На странице 
https://github.com/max197616/extfilter/wiki/Extfilter-%D0%B2-cacti
написано

> Установите шаблоны из contrib/exfilter_cacti.tar.gz в cacti.

Проблема в том, что, например в версию 0.8.8b они не устанавливаются, т.к. не совпадает версия хэшей. Необходимо отредактировать файлы темплейтов, заменить hash_xx0025 --> hash_xx0024 в моем случае.
Надо добавить в wiki информацию из какой версии cacti сделан экспорт темплейтов, т.к. cacti ошибку выдает очень неочевидную.

**Comment by max197616** [comment]
Добавил.

**Comment by CEMEHOB** [comment]
Можно еще добавить такой текст:

> После импорта темплейтов, проверьте, что в Data Input Methods:
> ExtFilter - Reader statistics
> ExtFilter - Workers statistics
> правильный путь до snmpget

**Comment by CEMEHOB** [comment]
Поскольку в FreeBSD при установке из портов путь /usr/local/bin/snmpget

**Comment by max197616** [comment]
Добавил.

**Comment by CEMEHOB** [comment]
Отлично, спасибо!
