### ISSUE TITLE
what is potential values of with-dpdk_target?

### ISSUE THREAD

**Issue by kaijunzhan** [max197616/extfilter#5]
--with-dpdk_target

**Comment by 490** [comment]
@kaijunzhan 你好！请问你对 用nDPI分析统计DPDK抓来的数据包有没有什么思路呀，这位俄国大哥的程序有点难读😦

**Comment by kaijunzhan** [comment]
用DPDK作開始的大部粗略分析。然後用DPI作精準分析

**Comment by max197616** [comment]
This is the value that was set when making DPDK.
