### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by mmanoj** [max197616/extfilter#6]
Hi ,

I'm getting below error while compile, seeking your advice.

/usr/include/Poco/Logger.h:469:13: note:   candidate expects 0 arguments, 2 provided
main.cpp:1179:93: error: no matching function for call to ‘Poco::Logger::warning(const char [58], std::__cxx11::string&, std::__cxx11::string&)’
       logger().warning("Pattern '%s' already present in the database from file %s",insert,fn);
                                                                                             ^
In file included from ../include/worker.h:10:0,
                 from main.cpp:19:
/usr/include/Poco/Logger.h:397:13: note: candidate: void Poco::Logger::warning(const string&)
 inline void Logger::warning(const std::string& msg)
             ^
/usr/include/Poco/Logger.h:397:13: note:   candidate expects 1 argument, 3 provided
/usr/include/Poco/Logger.h:451:13: note: candidate: bool Poco::Logger::warning() const
 inline bool Logger::warning() const
             ^
/usr/include/Poco/Logger.h:451:13: note:   candidate expects 0 arguments, 3 provided
main.cpp:1181:85: error: no matching function for call to ‘Poco::Logger::error(const char [45], std::__cxx11::string&, int&, std::__cxx11::string&)’
       logger().error("Failed to add '%s' from line %d from file %s",insert,lineno,fn);
                                                                                     ^
In file included from ../include/worker.h:10:0,
                 from main.cpp:19:
/usr/include/Poco/Logger.h:391:13: note: candidate: void Poco::Logger::error(const string&)
 inline void Logger::error(const std::string& msg)
             ^
/usr/include/Poco/Logger.h:391:13: note:   candidate expects 1 argument, 4 provided
/usr/include/Poco/Logger.h:445:13: note: candidate: bool Poco::Logger::error() const
 inline bool Logger::error() const
             ^
/usr/include/Poco/Logger.h:445:13: note:   candidate expects 0 arguments, 4 provided
main.cpp:1189:84: error: no matching function for call to ‘Poco::Logger::debug(const char [47], std::__cxx11::string&, int&, std::__cxx11::string&)’
       logger().debug("Updated domain: '%s' from line %d from file %s",str,lineno,fn);
                                                                                    ^
In file included from ../include/worker.h:10:0,
                 from main.cpp:19:
/usr/include/Poco/Logger.h:415:13: note: candidate: void Poco::Logger::debug(const string&)
 inline void Logger::debug(const std::string& msg)
             ^
/usr/include/Poco/Logger.h:415:13: note:   candidate expects 1 argument, 4 provided
/usr/include/Poco/Logger.h:469:13: note: candidate: bool Poco::Logger::debug() const
 inline bool Logger::debug() const
             ^
/usr/include/Poco/Logger.h:469:13: note:   candidate expects 0 arguments, 4 provided
Makefile:376: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: Leaving directory '/opt/dpdk-ndpi/extfilter/src'
Makefile:342: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by max197616** [comment]
What version of POCO do you use?

**Comment by mmanoj** [comment]
I installed via apt-get install poco*

**Comment by mmanoj** [comment]
@max197616 

Can you advice how to check the version, and what version your software support ?

**Comment by max197616** [comment]
As I wrote in readme (in russian) - needed version of poco should be 1.6 or higher.

**Comment by mmanoj** [comment]
Thanks, I will try to install latest poco and try, look like it install 1.5. I will try fresh again and update you the result.

**Comment by mmanoj** [comment]
Hi, 
I install poco 1.7 (latest available) and while compiling getting below error:

mv -f .deps/sender.Tpo .deps/sender.Po
g++ -DHAVE_CONFIG_H -I. -I../include  -I../ -I../nDPI/src/include -I/opt/dpdk/dpdk-stable-16.11.1/build/include   -std=c++11 -O3 -Wall -pthread -msse -msse2 -msse3 -mssse3 -MT sendertask.o -MD -MP -MF .deps/sendertask.Tpo -c -o sendertask.o sendertask.cpp
In file included from sendertask.cpp:20:0:
../include/sendertask.h:174:3: error: ‘__m128i’ does not name a type
   __m128i ipv6;
   ^~~~~~~
../include/sendertask.h:179:3: error: ‘__m128i’ does not name a type
   __m128i ipv6;
   ^~~~~~~
../include/sendertask.h: In constructor ‘RedirectNotificationG::RedirectNotificationG(int, int, void*, void*, int, uint32_t, uint32_t, int, char*, bool)’:
../include/sendertask.h:120:13: error: ‘union RedirectNotificationG::<anonymous>’ has no member named ‘ipv6’; did you mean ‘ipv4’?
    _user_ip.ipv6 = _mm_loadu_si128((__m128i *)user_ip);
             ^~~~
../include/sendertask.h:120:37: error: ‘__m128i’ was not declared in this scope
    _user_ip.ipv6 = _mm_loadu_si128((__m128i *)user_ip);
                                     ^~~~~~~
../include/sendertask.h:120:46: error: expected primary-expression before ‘)’ token
    _user_ip.ipv6 = _mm_loadu_si128((__m128i *)user_ip);
                                              ^
../include/sendertask.h:120:54: error: ‘_mm_loadu_si128’ was not declared in this scope
    _user_ip.ipv6 = _mm_loadu_si128((__m128i *)user_ip);
                                                      ^
../include/sendertask.h:121:12: error: ‘union RedirectNotificationG::<anonymous>’ has no member named ‘ipv6’; did you mean ‘ipv4’?
    _dst_ip.ipv6 = _mm_loadu_si128((__m128i *)dst_ip);
            ^~~~
../include/sendertask.h:121:45: error: expected primary-expression before ‘)’ token
    _dst_ip.ipv6 = _mm_loadu_si128((__m128i *)dst_ip);
                                             ^
Makefile:375: recipe for target 'sendertask.o' failed
make[1]: *** [sendertask.o] Error 1
make[1]: Leaving directory '/opt/extfilter/src'
Makefile:341: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by max197616** [comment]
I think that you are compiling the extfilter on the cpu without sse2 instructions.

**Comment by mmanoj** [comment]
Hi @max197616 

It's VM with virtual box, I already enable SSE2 instructions. I will try fresh again and update you.
